### ISSUE TITLE
Minor Export Page Bug

### ISSUE THREAD

**Issue by Freakrider** [ngandrass/moodle-quiz_archiver#12]
If you sneak into the Attempt Export page by editing the url "&mode=archiver" like this 
https://sandbox.moodlenrw.de/mod/quiz/report.php?id=29&mode=archiver

There is no visible indication that there is no attempt yet and you can still proceed. 

If you try to export, you will get a failed error and some SQL exceptions.

**Comment by ngandrass** [comment]
Thanks for reporting! I'll prepare a fix for the next release :+1:

**Comment by ngandrass** [comment]
Fixed by da6fee95cfa4b0c950f1af6c74c77235ca10fba5. Will be part of the next release :tada:
