### ISSUE TITLE
[Bug]: Error thrown on MySQL when starting the archiving process

### ISSUE THREAD

**Issue by PM84** [ngandrass/moodle-quiz_archiver#13]
### Quiz archiver moodle plugin version

2023121400

### Quiz archiver worker version

latest

### Worker service deployment method

Docker compose

### Moodle Version

4.3.2

### PHP Version

8.1

### Database

MySQL

### Operating system

Ubuntu 22.04

### What happened?

Expected behavior:

When starting the archiving process, the archiving will be started.

Actual behavior:
An error related to the field name "key" is thrown on a MySQL DB when starting the archiving process. "key" is a protected name in MySQL.

Additional information:

### Steps to reproduce

1. Run moodle on an MySQL DB
2. Start an archiving process
3. => Error occured, that the field key can not be used.

**Comment by ngandrass** [comment]
Thanks for your bug report :)

This issue has been fixed with quiz_archiver v1.2.3 (20240112). Please upgrade and try again.

Release v1.2.3: https://github.com/ngandrass/moodle-quiz_archiver/releases/tag/v1.2.3
Commit: a76debd527f3cb7dab03d2ebb5439337a8ac4039

**Comment by PM84** [comment]
Yes, your're right! Thanks for your help
