### ISSUE TITLE
[Request]: Changing GET request length

### ISSUE THREAD

**Issue by braunJ42** [ngandrass/moodle-quiz_archiver#14]
### Description

When trying to archive a bigger quiz (300+ attempts) the final GET request gets too long (10.000+) as it includes all the attempt-IDs of the quiz, so it crashes and ends with an HTTP 414 error.

Is there a chance that this could be changed in the future?

**Comment by ngandrass** [comment]
Hi,

thanks for your report. Sounds like it is time to create a test quiz with **a lot** of attempts ;)

I assume you are talking about the final step of fetching the metadata for all attempts? If so, it should be easy to paginate the attempt metadata queries :)

**Comment by braunJ42** [comment]
Hi,

thanks for your quick response :) 

Yes, it's the final step of fetching the metadata for all attempts.
And as we have even bigger quizzes (900+ attempts) it would be awesome if we could get it to work somehow :)

**Comment by ngandrass** [comment]
Attempt metadata is now processed in batches of 100 attempts, as per commit [d4e45b4120b008639de026b08e5586bb7c804c3d](https://github.com/ngandrass/moodle-quiz-archive-worker/commit/d4e45b4120b008639de026b08e5586bb7c804c3d).

[Version 1.3.3](https://github.com/ngandrass/moodle-quiz-archive-worker/releases/tag/v1.3.3) of the [quiz archive worker](https://github.com/ngandrass/moodle-quiz-archive-worker) was just released and includes this fix. You can simply update to the `latest` Docker image from [Docker Hub](https://hub.docker.com/r/ngandrass/moodle-quiz-archive-worker). An upgrade of the Moodle plugin is not required.

For testing, I extended the [quiz archiver reference course](https://github.com/ngandrass/moodle-quiz_archiver?tab=readme-ov-file#testing) to include quizzes with 100, 250, 500, and 1000 attempts. All quizzes, even with 1000 attempts, were now exported correctly :tada: 

Theoretically we can still encounter problems if the resulting quiz archive outgrows certain thresholds, such as the maximum file size your Moodle accepts. Please open another issue, if you encounter such problems.
