### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by bellanz80** [ngandrass/moodle-quiz_archiver#16]
Moodle 4.3.2
"No se puede encontrar registro de datos en la tabla external_serv'ices de la base de datos."
Cannot find data record in the external_services table in the database.

**Comment by ngandrass** [comment]
Without any additional information, I can not debug or reproduce this, sorry.

The first things I'd check would be:

- Did you execute the Moodle upgrade routine after placing the plugin inside your Moodle directory?
- Have you followed the configuration instructions (creating webservice user, ...)?
  - See: https://github.com/ngandrass/moodle-quiz_archiver?tab=readme-ov-file#configuration
- On which page does this error occur? How can I reproduce the error?

Please consider re-filing this bug report using the appropriate [Bug Report Template](https://github.com/ngandrass/moodle-quiz_archiver/issues/new?assignees=&labels=&projects=&template=bugreport.yml&title=%5BBug%5D%3A+).

**Comment by ngandrass** [comment]
I accidentally ran into the same error message during some work on #15. To me it seems, like you did not configure the webservice for the plugin properly.

I added a new error message, to catch this case. Also, once #15 is merged, the configuration of the plugin will get **a lot** easier :)

**Comment by bellanz80** [comment]
Very thank's!
