### ISSUE TITLE
De translation 100% low hanging fruit quick win

### ISSUE THREAD

**Issue by lucaboesch** [ngandrass/moodle-quiz_archiver#19]
Upload https://github.com/ngandrass/moodle-quiz_archiver/blob/master/lang/de/quiz_archiver.php on [lang.moodle.org](https://lang.moodle.org/local/amos/stage.php)
Thus, the language file is in the official Moodle translation DB and the language will show as 100% Translated (which it is).

Thanks!

**Comment by ngandrass** [comment]
Thanks for your suggestion. I submitted the language file as `#54749 Import of existing full German translation` :)

**Comment by ngandrass** [comment]
See: https://lang.moodle.org/local/amos/contrib.php?id=54749
