### ISSUE TITLE
consider adding github actions support (it's free and very useful)

### ISSUE THREAD

**Issue by danmarsden** [ngandrass/moodle-quiz_archiver#2]
Some of the tests run by the Moodle.org plugins db can be run via github actions on each commit in your github repo. Enabling this helps you to make sure future changes to your plugin will continue to follow the guidelines.

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by ngandrass** [comment]
Thanks for your suggestion!

I integrated the workflow and it seems to work. As expected, it detects various code style related issues. I'll dig through it after I finished work on the remaining issues :)

**Comment by ngandrass** [comment]
I tackled the, in my opinion, most relevant suggestions. Removing the underscores from all variable names, however, is nothing I'll do right now :see_no_evil:
