### ISSUE TITLE
There should be a redirect after a HTTP POST query

### ISSUE THREAD

**Issue by ndunand** [ngandrass/moodle-quiz_archiver#29]
Hello @ngandrass ,

Just something that I noticed today: When posting the form to create a new task, I noticed that the resulting URL is `/mod/quiz/report.php` , instead of the full URI `/mod/quiz/report.php?id{QUIZ_CMID}&mode=archiver`, i.e. the page displayed is the result of the HTTP POST query and does not display the GET query string. I can therefore not (at least not immediately) for instance copy and send the URL of this page to say, a colleague.

Then, if by mistake I then use the browser's reload feature instead of the "Archives" table's reload button, the previous HTTP POST is played again, and a new job is created.

I think that it is in general good practice in a web app to redirect to a full GET query after the HTTP POST has been processed.

I noticed the same after confirming a job suppression (testing the above I created many duplicate queued jobs ;) ).

What do you think?

**Comment by ngandrass** [comment]
Thanks for your suggestion! Sounds like a valid and very good improvement to me :+1:

**Comment by ngandrass** [comment]
Implemented as suggested and merged with #32. Will be part of the next release :tada:
