### ISSUE TITLE
[Request]: Make idnumber a variable for filename pattern

### ISSUE THREAD

**Issue by melanietreitinger** [ngandrass/moodle-quiz_archiver#33]
### Description

It could be useful to have `idnumber `as a variable for `job_preset_archive_filename_pattern` as well!

**Comment by ngandrass** [comment]
Sound good to me. Thanks for your suggestion :+1:

**Comment by ngandrass** [comment]
Implemented with #54. Will be part of the upcoming release (probably today) :tada:
