### ISSUE TITLE
[Request]: Harmonize versions of plugin and worker

### ISSUE THREAD

**Issue by melanietreitinger** [ngandrass/moodle-quiz_archiver#34]
### Description

Currently the plugin has the version 1.4.0 whereas the worker needs version >= v1.6.0.
This is quite confusing. It could help reducing errors if plugin and worker shared the same version numbers.

**Comment by ngandrass** [comment]
Ok, then I'll harmonize the version numbers as discussed with the next major release :)

**Comment by ngandrass** [comment]
* Added to docs
* Upcoming release will be `2.0.0` for both plugins to have a clean version cut
