### ISSUE TITLE
[Request]: User / Teacher documentation of the plugin

### ISSUE THREAD

**Issue by melanietreitinger** [ngandrass/moodle-quiz_archiver#39]
### Description

Would it perhaps be a good idea to put a link to the official docs page (https://docs.moodle.org/404/de/Quiz_Archiver_Plugin) in the plugin?
It could be placed on top of the archiver page itself, so every teacher can see it:

![grafik](https://github.com/user-attachments/assets/31c393e6-ac50-45bd-a967-a0bb58678337)

**Comment by ngandrass** [comment]
Hi,

thanks for your suggestion. So it seems that Julia had success in having a documentation page created within the Moodle wiki, as announced here: https://github.com/ngandrass/moodle-quiz_archiver/issues/21#issuecomment-2293172805 :)

And it seems like someone already documented some stuff, including a video tutorial. Nice :+1:

Currently the plugin already links from the admin settings page to the README for admin related topics:
![image](https://github.com/user-attachments/assets/19eff783-8911-4a2d-b66e-ca8c8e0f44a4)

For users/teachers, a small [usage section within the README](https://github.com/ngandrass/moodle-quiz_archiver?tab=readme-ov-file#usage) exists. A proper extensive user documentation, however, is yet to be created. I already had some ideas for this.

Other larger plugins tend to handle it by creating a documentation within the source code repository and serve it on a separate web site, e.g., STACK with https://docs.stack-assessment.org/. This allows the documentation to stay in sync with the actual plugin versions and hopefully prevents it from becoming outdated. I'd imagine creating such a documentation system for this plugin as well and link to it from both the plugin itself (quiz archiving page) as well as the Moodle wiki page.

Does that sound like an idea? If so, I could setup the basic system and create a base documentation that everyone can freely extend as desired.

**Comment by ngandrass** [comment]
And to collect it somewhere... These are the docs / information the community already created that I'm aware of:

* https://docs.moodle.org/404/de/Quiz_Archiver_Plugin
* https://fhpcast.fh-potsdam.de/static/mh_default_org/engage-player/71a83538-f036-4e91-aff2-acdd13c13e96/bfb76901-f271-40ec-9bc3-25459f2b5285/QuizArchiver.mp4
* https://moodlenrw.de/course/view.php?id=125
* https://gandrass.de/#pub-Gandrass2024QuizArchiverMUA

**Comment by melanietreitinger** [comment]
> Does that sound like an idea? If so, I could setup the basic system and create a base documentation that everyone can freely extend as desired.

Yes, that sounds perfect! 😊 
Teachers have a direct link to their docs as well and the docs will be up-to-date! 👍

**Comment by ngandrass** [comment]
I created a quick draft for the documentation using [mkdocs](https://www.mkdocs.org/).

![image](https://github.com/user-attachments/assets/897fc651-615e-4635-b45a-ffa8631c4e8f)

I need to focus on some other tasks now but will get back to the documentation. My plan is to provide a basic version that contains the already existing information and will be available here on GitHub. This way everyone can contribute and extend the docs :)

**Comment by ngandrass** [comment]
I finally found some time to write up the new documentation. You can access the first work-in-progress version here: https://ngandrass.github.io/moodle-quiz_archiver/ :tada: 

I'd highly appreciate if you find some time to navigate through it and provide some feedback. If everything looks fine, I'll shorten the `README.md` file and create links to the new docs page from within the `README.md` and the Moodle plugin.

**Comment by ngandrass** [comment]
Ok, there seems to be a problem with the assets (images) right now. Works local, but not on GitHub pages...

I'll look into that and get back to you here...

**Comment by ngandrass** [comment]
Problem fixed. The docs are now served under a custom domain: https://quizarchiver.gandrass.de/

Everything looks fine now :+1:

**Comment by melanietreitinger** [comment]
@ngandrass Thanks a lot! I did a quick look around - this looks great! 👍 

Before I go into the detail: what is the best way to give you feedback on issues like content or typos?
Here in the comments?

**Comment by ngandrass** [comment]
Merged with #51 

Will be part of the upcoming release after #52 is finished
