### ISSUE TITLE
strings file does not allow for concatenation (it's not really treated as a php file.)

### ISSUE THREAD

**Issue by danmarsden** [ngandrass/moodle-quiz_archiver#4]
https://github.com/ngandrass/moodle-quiz_archiver/blob/master/lang/en/quiz_archiver.php#L27-L28

string concatentaion in the lang packs is not allowed - it causes problems for the Moodle translation tool

eg:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

each string must be contained within one set of quotes eg:
$string['test'] = "sometext somemoretext"; 

This is a blocker for plugins db approval.

**Comment by ngandrass** [comment]
Fixed with 611659858ae0d2f637f722122f13a37690f9abf4

Thanks for your report! :tada:
