### ISSUE TITLE
[Request]: Integrate student idnumber in quiz report metadata header table

### ISSUE THREAD

**Issue by ngandrass** [ngandrass/moodle-quiz_archiver#49]
### Description

In addition to #33, the idnumber should also be part of the header that is displayed on top of each attempt report PDF.

**Comment by natapak** [comment]
This would be a great feature to have.
I've tried the plugin and it works very well, but unfortunately we need a student idnumber to use it.

**Comment by ngandrass** [comment]
@natapak Thanks for showing interest in this feature :+1:  I'm currently on vacation but will work on this once I'm back :)

**Comment by ngandrass** [comment]
Implemented with #54. Will be part of the upcoming release (probably today) :tada:
