### ISSUE TITLE
Improvement - adminsetting for auto-deleting archives

### ISSUE THREAD

**Issue by martinoesterreicher** [ngandrass/moodle-quiz_archiver#6]
It would be nice if there was an admin setting, which can be activated and if its active a time setting after which archives are deleted automatically.
For teachers it should show in a column when the archive will be deleted automatically.

**Comment by ngandrass** [comment]
That should be rather easy to implement using another scheduled task. I'll put it on the TODO list for the next release :)

**Comment by martinoesterreicher** [comment]
Awesome, thanks. :)

**Comment by ngandrass** [comment]
The automatic archive deletion is implemented with the just released [version 1.2.0](https://github.com/ngandrass/moodle-quiz_archiver/releases/tag/v1.2.0) :tada:
