### ISSUE TITLE
Improvement - adminsetting for what is archived by default

### ISSUE THREAD

**Issue by martinoesterreicher** [ngandrass/moodle-quiz_archiver#7]
It would be nice if there was an admin setting, where one can select which things to archives should be default. 
E.g. so that the .mbz can be set to not checked to be included in the archive be default.

**Comment by ngandrass** [comment]
This is already covered by release [v1.1.0](https://github.com/ngandrass/moodle-quiz_archiver/releases/tag/v1.1.0) :tada: 

See [Archive job presets](https://github.com/ngandrass/moodle-quiz_archiver?tab=readme-ov-file#archive-job-presets-global-defaults--policies) inside the README for more details :)

**Comment by martinoesterreicher** [comment]
Oh, that sounds awesome, thanks. :)
